### ISSUE TITLE
XhrIoPool is not a constructor  at new WebChannelConnection

### ISSUE THREAD

**Issue by joseluismurillorios** [codediodeio/geofirex#35]
Hello, I'm getting error when request a collection:

`firebase.initializeApp(FIREBASE_CONFIG);`

`export const db = firebase.firestore();`
`export const geo = geofirex.init(firebase);`

`const opinions = geo.collection('opinions'); // Here`

`Firestore (4.10.1) 2019-03-14T06:35:54.962Z: INTERNAL UNHANDLED ERROR:  TypeError: _firebase_webchannel_wrapper__WEBPACK_IMPORTED_MODULE_0__.XhrIoPool is not a constructor
    at new WebChannelConnection (https://ryrapp.herokuapp.com/bundle.js:13340:21)
    at BrowserPlatform../node_modules/@firebase/firestore/dist/esm/src/platform_browser/browser_platform.js.BrowserPlatform.loadConnection (https://ryrapp.herokuapp.com/bundle.js:13271:32)
    at FirestoreClient../node_modules/@firebase/firestore/dist/esm/src/core/firestore_client.js.FirestoreClient.initializeRest (https://ryrapp.herokuapp.com/bundle.js:4206:14)
    at https://ryrapp.herokuapp.com/bundle.js:4097:54`

Everything works fine in development. There's nothing else pointing to geofirex, only that line.

**Comment by joseluismurillorios** [comment]
It was a problem with firebase version mismatch on my computer. Apologies.
